SOURCES=mm.c ds_allocator.c malloc.c
OUTPUT=mm.a
include $(ROOTDIR)/hobo_kernel.mk
SOURCES=early_putc.c libc_memfuncs.c libc_strfuncs.c freebsd_printf.c printf.c quicksort.c
OUTPUT=lib.a
include $(ROOTDIR)/hobo_kernel.mk
