SOURCES=main.c noarch.c console.c mutex.c bs_commands.c interrupt.c timer.c init_funcs.c syms.c
SOURCES+=vers.c
OUTPUT=core.a
INCLUDES+=-I$(ROOTDIR)/../common/include
EXTRA_FILES=vers.c

include $(ROOTDIR)/hobo_kernel.mk
